FROM httpd
ARG UNAME=ws_user
ARG UID=1000
ARG GID=1000
COPY ws/*.conf /usr/local/apache2/conf/
RUN groupadd -g $GID -o $UNAME && useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME

EXPOSE 80
EXPOSE 443
