---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Home Sweet Home Dashboard"
subtitle: "HSH"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: false
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

stylesheet:                                      
  - "assets/custom.css"

columns: "3"
theme: "default"
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

# Optional message
#message:
#  #url: https://b4bz.io
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Benvenuto !"
#  icon: "fa fa-grin"
#  content: "Da qui puoi accedere a tutti gli applicativi che gestiscono la tua casa!</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
#links:
#  - name: "Home"
#    icon: "fab fa-home"
#    url: "/"
#    #target: "_blank" # optional html a tag target attribute
#  - name: "Github"
#    icon: "fab fa-github"
#    url: "https://github.com/esposimo/hsh-docker"
#    target: "_blank"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Infrastructure"
    icon: "fas fa-cloud"
    items:
      - name: "Unifi Console"
        subtitle: "Management of VLAN, Wifi, etc"
        url: "https://www.reddit.com/r/selfhosted/"
        logo: assets/icons/ubiquiti.svg
        keywords: "unifi console vlan wifi ethernet eth network"
        tag: "infr."
        target: "_blank"
      - name: Nginx Proxy Manager
        subtitle: "Configure your reverse proxy!"
        url: http://192.168.1.86:81/
        logo: assets/icons/npm.svg
        keywords: "nginx proxy web app ws webserver"
        tag: "infr."
        target: '_blank'
      - name: "MQTT Client"
        subtitle: "Connect to your mqtt broker!"
        url: "https://192.168.1.86:5601"
        logo: assets/icons/mqtt-hor.svg
        keywords: "mqtt Infrastructure manage monitor"
        tag: "infr."
        target: "_blank"
      - name: "Manage your Database"
        subtitle: "Connect to yours database"
        url: "https://192.168.1.86:5601"
        logo: assets/icons/adminer.svg
        keywords: "database admin Infrastructure manage monitor"
        tag: "infr."
        target: "_blank"
  - name: "Smart Home"
    icon: "fas fa-house"
    items:
      - name: "Home Assistant"
        subtitle: "Manage your smart home!"
        url: "https://hasmn.duckdns.org"
        logo: assets/icons/home-assistant.svg
        keywords: "ha home assistant smart light automation"
        tag: "home"
        target: "_blank"
      - name: "Kibana"
        subtitle: "Manage your metric data"
        url: https://mykibana.local
        logo: assets/icons/kibana-svgrepo-com.svg
        keywords: "kibana monitor search elastic"
        tag: "monitor"
        target: _blank
      - name: "Zigbee"
        subtitle: "Manage your zigbee network"
        url: http://myzigbee2mqtt.local
        logo: assets/icons/zigbee2mqtt.svg
        keywords: "zigbee network lan"
        tag: "infr."
        target: _blank
      - name: "Grafana"
        subtitle: "Monitor your smart home"
        url: "http://mygrafana.local"
        logo: assets/icons/grafana.svg
        keywords: "monitor energy power data search"
        tag: "monitor"
        target: _blank
  - name: "Tools"
    icon: "fas fa-tools"
    items:
      - name: "Portainer"
        subtitle: "See your docker host"
        url: "http://myport.local"
        logo: assets/icons/portainer.svg
        keywords: "docker k8 port"
        tag: "infr."
        target: "_blank"
      - name: "Cloudflare"
        subtitle: "Gestisci accoutn Cloudflare"
        url: https://dash.cloudflare.com/<myurl>
        logo: assets/icons/cloudflare.svg
      - name: "Backup"
        subtitle: "Gestisci i tuoi backup"
        url: https://myduplicati.local
        logo: assets/icons/duplicati.svg
        target: _blank
      - name: "Password"
        subtitle: "Manage password"
        url: http://192.168.1.86:3880
        logo: assets/icons/bitwarden-v2-svgrepo-com.svg
        target: _blank
  - name: "Videogames"
    icon: "fas fa-gamepad"
    items:
      - name: "Xbox"
        subtitle: "xbox.com"
        url: https://xbox.com
        logo: assets/icons/xbox-svgrepo-com.svg
        keywords: "xbox game"
        tag: "games"
        target: "_blank"
      - name: "Playstation"
        subtitle: "playstation.it"
        url: https://www.playstation.com/it-it/
        logo: assets/icons/playstation-svgrepo-com.svg
        keywords: "ps5 ps playstation game"
        tag: "games"
        target: "_blank"
      - name: "Nintendo"
        subtitle: "nintendo.it"
        url: https://www.nintendo.it/
        logo: assets/icons/nintendo-svgrepo-com.svg
        keywords: "nintendo mario game"
        tag: "games"
        target: "_blank"
  - name: "Video"
    icon: "fas fa-video"
    items:
      - name: "Youtube"
        subtitle: "youtube.com"
        url: https://www.youtube.com
        logo: assets/icons/youtube-svgrepo-com.svg
        keywords: "youtube video movie"
        tag: "video"
        target: "_blank"
      - name: "Netflix"
        subtitle: "netflix.com"
        url: https://www.netflix.com
        logo: assets/icons/netflix-icon-svgrepo-com.svg
        keywords: "netflix film serie tv video movie"
        tag: "video"
        target: "_blank"
      - name: "Disney"
        subtitle: "disneyplus.com"
        url: https://www.disneyplus.com
        logo: assets/icons/disney-plus-svgrepo-com.svg
        keywords: "disney film serie tv video movie"
        tag: "video"
        target: "_blank"
      - name: "Prime Video"
        subtitle: "primevideo.com"
        url: https://www.primevideo.com
        logo: assets/icons/prime-svgrepo-com.svg
        keywords: "prime amazon film serie tv video movie"
        tag: "video"
        target: "_blank"
      - name: "Twitch"
        subtitle: "twitch.tv"
        url: https://www.twitch.tv/
        logo: assets/icons/twitch-svgrepo-com.svg
        keywords: "twitch game streaming gamers video movie"
        tag: "video"
        target: "_blank"          

